# 演示样本，凭据均为伪造值
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: production
type: Opaque
data:
  db-password: UHIwZF94SllMdjYxOXFjUzY=
  redis-password: TWZaMDFGMXhZUXpoUkpZUEdIbkI=
  jwt-secret: SEgwcHJPWHpCMU1WMnp2M2t6VHpPSVFPWDQzUFplOFYyOXJNeTlvMmtsOFBmY2ZW
